name: Tests
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    services:
      redis:
        image: redis

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
        env:
          REDIS_URL: redis://redis:6379
